Repository ruang-guru/sendbird-uikit-react, pull requests merged in 2021-11, with the labels that each got.

#37 fix: remove Thumbnail max-width and move Thumbnail and FileViewer utils to rogu/utils
  src/rogu/ui/FileViewer/index.jsx
  src/rogu/ui/FileViewer/types.js
  src/rogu/ui/ImageRenderer/index.jsx
  src/rogu/ui/MessageContent/index.tsx
  src/rogu/ui/TextMessageItemBody/index.scss
  src/rogu/utils/fileType.ts
  src/rogu/utils/index.ts
  src/rogu/utils/messageType.ts
Labels: refactor

#41 feat(component): buble chat message for replied message text
  src/rogu/smart-components/Conversation/hooks/useInitialMessagesFetch.js
  src/rogu/ui/MessageContent/index.tsx
  src/rogu/ui/TextMessageItemBody/index.scss
  src/rogu/ui/TextMessageItemBody/index.tsx
  src/rogu/utils/message.ts
  src/rogu/utils/messageType.ts
Labels: feature

#40 feat(component): link preview before sending a link
  package-lock.json
  package.json
  src/rogu/smart-components/Conversation/components/MessageInputWrapper.tsx
  src/rogu/ui/Label/stringSet.js
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/MessageInput/index.scss
  src/rogu/ui/MessageInput/utils.js
  src/rogu/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
  src/rogu/ui/OGMessageItemBody/index.scss
  src/rogu/ui/OGMessageItemBody/index.tsx
  yarn.lock
Labels: feature

#42 feat(component): Add chat archived banner and restyle admin message
  __mocks__/localizationMock.js
  __mocks__/messagesMock.js
  __mocks__/themeMock.js
  src/rogu/smart-components/Conversation/components/ArchivedBanner.jsx
  src/rogu/smart-components/Conversation/components/archived-banner.scss
  src/rogu/smart-components/Conversation/index.jsx
  src/rogu/smart-components/Conversation/stories/index.stories.js
  src/rogu/ui/AdminMessage/__tests__/AdminMessage.spec.js
  src/rogu/ui/AdminMessage/__tests__/__snapshots__/AdminMessage.spec.js.snap
  src/rogu/ui/AdminMessage/adminMessageDummyData.mock.js
  src/rogu/ui/AdminMessage/index.jsx
  src/rogu/ui/AdminMessage/index.scss
  src/rogu/ui/AdminMessage/stories/AdminMessage.stories.js
  src/rogu/ui/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
  src/rogu/ui/FileViewer/__tests__/__snapshots__/FileViewer.spec.js.snap
  src/rogu/ui/FileViewer/data.mock.js
  src/rogu/ui/FileViewer/index.scss
  src/rogu/ui/ImageRenderer/index.jsx
  src/rogu/ui/ImageRenderer/index.scss
  src/rogu/ui/Label/stringSet.js
  src/rogu/ui/MessageContent/stories/MessageContent.stories.js
  src/rogu/ui/ThumbnailMessageItemBody/index.scss
  src/rogu/ui/ThumbnailMessageItemBody/index.tsx
Labels: bug, feature

#39 feat: add from=chatroom query and menu item 'View'
  src/rogu/ui/AssignmentMessageItemBody/index.tsx
  src/rogu/ui/Icon/index.jsx
  src/rogu/ui/Icon/type.js
  src/rogu/ui/MaterialMessageItemBody/index.tsx
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/MessageItemMenu/index.tsx
  src/rogu/utils/assignmentMaterial.ts
  src/svgs/rogu-icon-view.svg
Labels: feature

#43 fix: update modal z-index
  package-lock.json
  src/rogu/ui/Modal/index.scss
Labels: bug

#46 fix: hide bubble arrow when class archived
  src/rogu/ui/ContextMenu/index.scss
  src/rogu/ui/ContextMenu/items/MenuItems.jsx
  src/rogu/ui/MessageContent/index.scss
  src/rogu/ui/MessageContent/index.tsx
Labels: feature

#44 feat: render url as LinkLabel
  src/rogu/ui/FileViewer/__tests__/__snapshots__/FileViewer.spec.js.snap
  src/rogu/ui/LinkLabel/__tests__/LinkLabel.spec.js
  src/rogu/ui/LinkLabel/__tests__/__snapshots__/LinkLabel.spec.js.snap
  src/rogu/ui/LinkLabel/index.jsx
  src/rogu/ui/LinkLabel/index.scss
  src/rogu/ui/LinkLabel/stories/LinkLabel.stories.js
  src/rogu/ui/MessageContent/index.tsx
  src/rogu/ui/TextMessageItemBody/index.tsx
  src/rogu/utils/index.ts
  src/rogu/utils/message.ts
  src/rogu/utils/messageType.ts
  src/rogu/utils/url.spec.js
  src/rogu/utils/url.ts
Labels: feature

#49 fix(component): fix label guru not next to name
  src/rogu/ui/MessageContent/index.scss
  src/rogu/ui/MessageContent/index.tsx
Labels: bug

#48 fix(component): limit input 3000 characters
  src/rogu/ui/MessageInput/index.jsx
Labels: bug

#47 fix: Attachment button out of place in small screen
  src/rogu/ui/Icon/index.jsx
  src/rogu/ui/Icon/type.js
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/MessageInput/index.scss
  src/styles/_color-themes.scss
  src/svgs/rogu-icon-send.svg
Labels: bug

#52 fix: refine unread notification string and hover color
  __mocks__/themeMock.js
  src/rogu/smart-components/Conversation/components/notification.scss
  src/rogu/smart-components/Conversation/dux/reducers.js
  src/rogu/ui/FileViewer/index.jsx
Labels: bug

#53 fix: hide message option in chained bubble message if channel is frozen
  src/rogu/ui/MessageContent/index.tsx
Labels: bug

#55 fix: typing indicator not seen
  src/rogu/smart-components/Conversation/components/TypingIndicator.jsx
  src/rogu/smart-components/Conversation/components/archived-banner.scss
  src/rogu/smart-components/Conversation/index.scss
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/MessageInput/index.scss
Labels: bug

#56 fix(style): admin message styling
  src/rogu/ui/AdminMessage/index.scss
  src/rogu/ui/MessageContent/index.tsx
Labels: bug

#60 fix(component): hide EMPTY_MESSAGE caption appearing in web when media message sent from android
  src/rogu/ui/MessageContent/index.tsx
Labels: bug

#61 fix: refine archive banner width
  src/rogu/smart-components/Conversation/components/archived-banner.scss
Labels: bug

#62 feat: add message reply with image attachment
  src/rogu/smart-components/Conversation/components/MessageHOC.jsx
  src/rogu/smart-components/Conversation/hooks/useSendFileMessageCallback.js
  src/rogu/smart-components/Conversation/hooks/useSendMessageCallback.js
  src/rogu/ui/MessageContent/index.tsx
  src/rogu/ui/MessageInput/RepliedMessagePreview.tsx
  src/rogu/ui/MessageInput/__tests__/MessageInput.spec.js
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/MessageInput/index.scss
  src/rogu/ui/RepliedMessageItemBody/index.tsx
  src/rogu/ui/TextMessageItemBody/index.tsx
  src/rogu/ui/ThumbnailMessageItemBody/index.tsx
  src/rogu/utils/message.ts
Labels: feature

#66 feat(component): Add feature reply to message image & video
  src/rogu/ui/Icon/index.jsx
  src/rogu/ui/Icon/type.js
  src/rogu/ui/ImageRenderer/index.scss
  src/rogu/ui/Label/stringSet.js
  src/rogu/ui/MessageInput/RepliedMessagePreview.tsx
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/RepliedMediaMessageItemBody/index.scss
  src/rogu/ui/RepliedMediaMessageItemBody/index.tsx
  src/rogu/ui/RepliedMessageItemBody/index.tsx
  src/rogu/ui/TextMessageItemBody/index.tsx
  src/rogu/ui/ThumbnailMessageItemBody/index.tsx
  src/rogu/utils/repliedMessage.ts
  src/svgs/rogu-icon-image.svg
  src/svgs/rogu-icon-video.svg
Labels: feature

#68 feat: handle scrolling to replied message
  src/rogu/smart-components/Conversation/components/ConversationScroll.jsx
  src/rogu/smart-components/Conversation/components/MessageHOC.jsx
  src/rogu/smart-components/Conversation/index.scss
  src/rogu/ui/MessageContent/index.tsx
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/RepliedMessageItemBody/index.tsx
  src/rogu/ui/TextMessageItemBody/index.tsx
  src/rogu/ui/ThumbnailMessageItemBody/index.tsx
  src/rogu/utils/repliedMessage.ts
Labels: feature

#69 fix(component): limit caption of image message to 930 characters
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/MessageInput/index.scss
Labels: bug

#70 feat: add message reply with link
  __mocks__/messagesMock.js
  src/rogu/ui/MessageContent/index.tsx
  src/rogu/ui/OGMessageItemBody/__tests__/OGMessageItemBody.spec.js
  src/rogu/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
  src/rogu/ui/OGMessageItemBody/index.scss
  src/rogu/ui/OGMessageItemBody/index.tsx
  src/rogu/ui/OGMessageItemBody/stories/OGMessageItemBody.stories.js
Labels: feature

#71 fix: add includeMetaArray param in each getMessagesByTimestamp call
  src/rogu/smart-components/Conversation/hooks/useHandleReconnect.js
  src/rogu/smart-components/Conversation/hooks/useScrollCallback.js
  src/rogu/smart-components/Conversation/hooks/useScrollDownCallback.js
Labels: feature

#72 fix: place words in a new line to avoid overflow
  src/rogu/ui/ClampedMessageItemBody/index.scss
Labels: feature

#74 fix: adjust link preview bubble responsiveness
  src/rogu/ui/OGMessageItemBody/index.scss
  src/rogu/ui/OGMessageItemBody/index.tsx
Labels: bug

#76 feat: copy the originalMessage only on replied message
  src/rogu/ui/MessageItemMenu/index.tsx
Labels: feature

#75 fix: (revision) adjust link preview bubble responsiveness
  src/rogu/ui/AssignmentMessageItemBody/index.scss
  src/rogu/ui/MessageContent/index.scss
  src/rogu/ui/OGMessageItemBody/index.scss
Labels: bug

#77 fix: ensure that file and thumbnail content are not rendered simultaneously
  src/rogu/ui/MessageContent/index.tsx
  src/rogu/ui/ThumbnailMessageItemBody/index.tsx
Labels: bug

#78 fix: use specific wording for view message menu
  __mocks__/localizationMock.js
  src/rogu/ui/ContextMenu/index.jsx
  src/rogu/ui/Label/stringSet.js
  src/rogu/ui/MessageItemMenu/index.tsx
Labels: bug

#79 fix: prevent bubble arrow menu overflowed in small screen
  src/rogu/ui/MessageContent/index.scss
Labels: bug

#80 release: v1.0.0
  CHANGELOG.md
  package.json
Labels: release

#81 fix: reply preview thumbnail shrinked when caption length is long
  src/rogu/ui/ContextMenu/index.scss
  src/rogu/ui/RepliedMediaMessageItemBody/index.scss
  src/rogu/ui/RepliedMediaMessageItemBody/index.tsx
Labels: bug

#82 release: v1.0.1
  CHANGELOG.md
  package.json
Labels: release

#83 fix: preserve line breaks and white spaces
  src/rogu/ui/ClampedMessageItemBody/__tests__/ClampedMessageItemBody.spec.js
  src/rogu/ui/ClampedMessageItemBody/__tests__/__snapshots__/ClampedMessageItemBody.spec.js.snap
  src/rogu/ui/ClampedMessageItemBody/index.scss
  src/rogu/ui/ClampedMessageItemBody/index.tsx
Labels: feature

#84 fix: remove line break character in replied message
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/utils/constants.ts
  src/rogu/utils/url.ts
Labels: bug

#85 fix: trim the replied message
  src/rogu/ui/MessageInput/index.jsx
  src/rogu/ui/RepliedMediaMessageItemBody/index.scss
  src/rogu/ui/RepliedMediaMessageItemBody/index.tsx
  src/rogu/utils/constants.ts
  src/rogu/utils/repliedMessage.ts
Labels: bug

#86 release: v1.0.2
  CHANGELOG.md
  package.json
Labels: release

#87 fix: make URL regex to include beyond URLs "port name"
  src/rogu/utils/constants.ts
Labels: bug

#88 release: v1.0.3
  CHANGELOG.md
  package.json
Labels: release
